/tracking/verbose 1

/vis/open OGL 1000x1000-0+0
/vis/viewer/set/autoRefresh false
/vis/verbose errors
/vis/drawVolume

/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/set/lightsVector -1 0 0
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 500

/vis/scene/add/axes 0 0 0 1 m
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2

/vis/scene/endOfEventAction accumulate 10000 

/vis/scene/add/eventID
/vis/scene/add/frame
/vis/set/colour
/vis/set/lineWidth

/vis/geometry/set/visibility World 0 false
/vis/geometry/set/colour Detector 1 0.8 0.8 1 0.3

/vis/viewer/set/style surface
/vis/viewer/set/hiddenMarker true
/vis/viewer/set/viewpointThetaPhi 130 90
/vis/viewer/set/autoRefresh true

/vis/verbose warnings
